# Generated by Django 3.2.6 on 2021-08-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sprites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_default', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('base_experience', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('abilities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trade.abilities')),
                ('forms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trade.forms')),
                ('held_items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trade.item')),
                ('moves', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trade.move')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trade.species')),
                ('sprites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trade.sprites')),
            ],
        ),
    ]
