# Generated by Django 3.2.6 on 2021-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='abilities',
        ),
        migrations.AddField(
            model_name='card',
            name='abilities',
            field=models.ManyToManyField(to='trade.Abilities'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='forms',
        ),
        migrations.AddField(
            model_name='card',
            name='forms',
            field=models.ManyToManyField(to='trade.Forms'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='held_items',
        ),
        migrations.AddField(
            model_name='card',
            name='held_items',
            field=models.ManyToManyField(to='trade.Item'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='moves',
        ),
        migrations.AddField(
            model_name='card',
            name='moves',
            field=models.ManyToManyField(to='trade.Move'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='species',
        ),
        migrations.AddField(
            model_name='card',
            name='species',
            field=models.ManyToManyField(to='trade.Species'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='sprites',
        ),
        migrations.AddField(
            model_name='card',
            name='sprites',
            field=models.ManyToManyField(to='trade.Sprites'),
        ),
    ]
